Rem --DDL change during upgrade
Rem
Rem upgrade_impl_ddl.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016 Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      upgrade_impl_ddl.sql
Rem
Rem    DESCRIPTION
Rem      DDL change during upgrade
Rem
Rem    NOTES
Rem      None
Rem

SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
  v_count     INTEGER;
BEGIN
  --add new column 'EMS_DASHBOARD.FEDERATION_SUPPORTED'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD' AND column_name='FEDERATION_SUPPORTED';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD ADD "FEDERATION_SUPPORTED" NUMBER(1,0) DEFAULT(0) NOT NULL';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD.FEDERATION_SUPPORTED exists already, no change is needed');
  END IF;

  --add new column 'EMS_DASHBOARD_TILE.FEDERATION_SUPPORTED'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE' AND column_name='FEDERATION_SUPPORTED';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE ADD "FEDERATION_SUPPORTED" NUMBER(1,0) DEFAULT(0) NOT NULL';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE.FEDERATION_SUPPORTED exists already, no change is needed');
  END IF;

  --add new column 'EMS_DASHBOARD.STATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD' AND column_name='STATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD ADD "STATE" NUMBER(1,0) DEFAULT(0) NOT NULL';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD.STATE exists already, no change is needed');
  END IF;

  EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('>>>DF DDL ERROR<<<');
    DBMS_OUTPUT.PUT_LINE('Failed to run the sql for federated dashboard support due to: '||SQLERRM);
    RAISE;
END;
/

--OMCSQ048: Indexes with a tenant_id key column must list it first
DECLARE
  v_count_index        INTEGER;
  v_count_position     INTEGER;
BEGIN
  
  -- EMS_DASHBOARD_LAST_ACCESS
  SELECT COUNT(1) INTO v_count_index FROM user_constraints WHERE constraint_name = 'EMS_DASHBOARD_LAST_ACCESS_PK' AND table_name = 'EMS_DASHBOARD_LAST_ACCESS';
  SELECT COUNT(1) INTO v_count_position FROM all_ind_columns WHERE INDEX_NAME = 'EMS_DASHBOARD_LAST_ACCESS_PK' AND TABLE_NAME = 'EMS_DASHBOARD_LAST_ACCESS' AND COLUMN_NAME = 'TENANT_ID' AND COLUMN_POSITION = 1;
  IF v_count_index=0 THEN
    DBMS_OUTPUT.PUT_LINE('constraint EMS_DASHBOARD_LAST_ACCESS_PK does not exist');
  ELSIF  v_count_position=1 THEN
    DBMS_OUTPUT.PUT_LINE('TENANT_ID has been already listed first in EMS_DASHBOARD_LAST_ACCESS_PK');
  ELSE
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_LAST_ACCESS DROP CONSTRAINT EMS_DASHBOARD_LAST_ACCESS_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_LAST_ACCESS ADD CONSTRAINT EMS_DASHBOARD_LAST_ACCESS_PK PRIMARY KEY(TENANT_ID, DASHBOARD_ID, ACCESSED_BY)';
    DBMS_OUTPUT.PUT_LINE('TENANT_ID is listed first in EMS_DASHBOARD_LAST_ACCESS_PK successfully!');
  END IF;
  
  -- EMS_DASHBOARD
  SELECT COUNT(1) INTO v_count_index FROM user_constraints WHERE constraint_name = 'EMS_DASHBOARD_PK' AND table_name = 'EMS_DASHBOARD';
  SELECT COUNT(1) INTO v_count_position FROM all_ind_columns WHERE INDEX_NAME = 'EMS_DASHBOARD_PK' AND TABLE_NAME = 'EMS_DASHBOARD' AND COLUMN_NAME = 'TENANT_ID' AND COLUMN_POSITION = 1;
  IF v_count_index=0 THEN
    DBMS_OUTPUT.PUT_LINE('constraint EMS_DASHBOARD_PK does not exist');
  ELSIF  v_count_position=1 THEN
    DBMS_OUTPUT.PUT_LINE('TENANT_ID has been already listed first in EMS_DASHBOARD_PK');
  ELSE
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD DROP CONSTRAINT EMS_DASHBOARD_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD ADD CONSTRAINT EMS_DASHBOARD_PK PRIMARY KEY(TENANT_ID, DASHBOARD_ID)';
    DBMS_OUTPUT.PUT_LINE('TENANT_ID is listed first in EMS_DASHBOARD_PK successfully!');
  END IF;
  
  -- EMS_DASHBOARD_FAVORITE
  SELECT COUNT(1) INTO v_count_index FROM user_constraints WHERE constraint_name = 'EMS_DASHBOARD_FAVORITE_PK' AND table_name = 'EMS_DASHBOARD_FAVORITE';
  SELECT COUNT(1) INTO v_count_position FROM all_ind_columns WHERE INDEX_NAME = 'EMS_DASHBOARD_FAVORITE_PK' AND TABLE_NAME = 'EMS_DASHBOARD_FAVORITE' AND COLUMN_NAME = 'TENANT_ID' AND COLUMN_POSITION = 1;
  IF v_count_index=0 THEN
    DBMS_OUTPUT.PUT_LINE('constraint EMS_DASHBOARD_FAVORITE_PK does not exist');
  ELSIF  v_count_position=1 THEN
    DBMS_OUTPUT.PUT_LINE('TENANT_ID has been already listed first in EMS_DASHBOARD_FAVORITE_PK');
  ELSE
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_FAVORITE DROP CONSTRAINT EMS_DASHBOARD_FAVORITE_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_FAVORITE ADD CONSTRAINT EMS_DASHBOARD_FAVORITE_PK PRIMARY KEY(TENANT_ID,DASHBOARD_ID,USER_NAME)';
    DBMS_OUTPUT.PUT_LINE('TENANT_ID is listed first in EMS_DASHBOARD_FAVORITE_PK successfully!');
  END IF;
  
  -- EMS_DASHBOARD_TILE
  SELECT COUNT(1) INTO v_count_index FROM user_constraints WHERE constraint_name = 'EMS_DASHBOARD_TILE_PK' AND table_name = 'EMS_DASHBOARD_TILE';
  SELECT COUNT(1) INTO v_count_position FROM all_ind_columns WHERE INDEX_NAME = 'EMS_DASHBOARD_TILE_PK' AND TABLE_NAME = 'EMS_DASHBOARD_TILE' AND COLUMN_NAME = 'TENANT_ID' AND COLUMN_POSITION = 1;
  IF v_count_index=0 THEN
    DBMS_OUTPUT.PUT_LINE('constraint EMS_DASHBOARD_TILE_PK does not exist');
  ELSIF  v_count_position=1 THEN
    DBMS_OUTPUT.PUT_LINE('TENANT_ID has been already listed first in EMS_DASHBOARD_TILE_PK');
  ELSE
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE DROP CONSTRAINT EMS_DASHBOARD_TILE_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE ADD CONSTRAINT EMS_DASHBOARD_TILE_PK PRIMARY KEY(TENANT_ID,TILE_ID)';
    DBMS_OUTPUT.PUT_LINE('TENANT_ID is listed first in EMS_DASHBOARD_TILE_PK successfully!');
  END IF;
  
  -- EMS_DASHBOARD_TILE_PARAMS
  SELECT COUNT(1) INTO v_count_index FROM user_constraints WHERE constraint_name = 'EMS_DASHBOARD_TILE_PARAMS_PK' AND table_name = 'EMS_DASHBOARD_TILE_PARAMS';
  SELECT COUNT(1) INTO v_count_position FROM all_ind_columns WHERE INDEX_NAME = 'EMS_DASHBOARD_TILE_PARAMS_PK' AND TABLE_NAME = 'EMS_DASHBOARD_TILE_PARAMS' AND COLUMN_NAME = 'TENANT_ID' AND COLUMN_POSITION = 1;
  IF v_count_index=0 THEN
    DBMS_OUTPUT.PUT_LINE('constraint EMS_DASHBOARD_TILE_PARAMS_PK does not exist');
  ELSIF  v_count_position=1 THEN
    DBMS_OUTPUT.PUT_LINE('TENANT_ID has been already listed first in EMS_DASHBOARD_TILE_PARAMS_PK');
  ELSE
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE_PARAMS DROP CONSTRAINT EMS_DASHBOARD_TILE_PARAMS_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE_PARAMS ADD CONSTRAINT EMS_DASHBOARD_TILE_PARAMS_PK PRIMARY KEY(TENANT_ID,TILE_ID,PARAM_NAME)';
    DBMS_OUTPUT.PUT_LINE('TENANT_ID is listed first in EMS_DASHBOARD_TILE_PARAMS_PK successfully!');
  END IF;
  
  -- EMS_PREFERENCE
  SELECT COUNT(1) INTO v_count_index FROM user_constraints WHERE constraint_name = 'EMS_PREFERENCES_PK' AND table_name = 'EMS_PREFERENCE';
  SELECT COUNT(1) INTO v_count_position FROM all_ind_columns WHERE INDEX_NAME = 'EMS_PREFERENCES_PK' AND TABLE_NAME = 'EMS_PREFERENCE' AND COLUMN_NAME = 'TENANT_ID' AND COLUMN_POSITION = 1;
  IF v_count_index=0 THEN
    DBMS_OUTPUT.PUT_LINE('constraint EMS_PREFERENCES_PK does not exist');
  ELSIF  v_count_position=1 THEN
    DBMS_OUTPUT.PUT_LINE('TENANT_ID has been already listed first in EMS_PREFERENCES_PK');
  ELSE
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_PREFERENCE DROP CONSTRAINT EMS_PREFERENCES_PK';
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_PREFERENCE ADD CONSTRAINT EMS_PREFERENCES_PK PRIMARY KEY(TENANT_ID, USER_NAME, PREF_KEY)';
    DBMS_OUTPUT.PUT_LINE('TENANT_ID is listed first in EMS_PREFERENCES_PK successfully!');
  END IF;
  
  EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('>>>DF DDL ERROR<<<');
    DBMS_OUTPUT.PUT_LINE('Failed to rebuild constraint due to error '||SQLERRM);
    RAISE;
END;
/

